# Generated by Django 3.1.2 on 2020-10-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201021_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
