# Generated by Django 3.0.7 on 2020-09-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200916_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=9)),
            ],
        ),
    ]
