# Generated by Django 3.1.1 on 2020-10-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.PositiveSmallIntegerField()),
                ('birthday', models.DateField()),
            ],
        ),
    ]
