# Generated by Django 3.1.1 on 2020-10-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201023_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog_member',
            },
        ),
    ]
