# Generated by Django 3.1.1 on 2020-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='book_title')),
                ('description', models.TextField(verbose_name='book_description')),
                ('author', models.CharField(max_length=50, verbose_name='book_author')),
            ],
        ),
    ]
