# Generated by Django 3.1.1 on 2020-09-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200924_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=50, verbose_name='book_author'),
            preserve_default=False,
        ),
    ]
