# Generated by Django 3.1.1 on 2020-09-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200924_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50, verbose_name='book_title'),
        ),
    ]
