# Generated by Django 3.1.2 on 2020-10-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_book_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='upload',
        ),
    ]
