# Generated by Django 3.1.1 on 2020-09-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200909_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=256),
        ),
    ]
