# Generated by Django 3.1.1 on 2020-09-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200909_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_name',
        ),
    ]
