# Generated by Django 3.1.2 on 2020-10-07 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201007_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 14, 4, 879898)),
        ),
    ]
