# Generated by Django 3.1.1 on 2020-09-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200911_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
