# Generated by Django 3.1.2 on 2020-10-05 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201005_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 16, 34, 36, 136492)),
        ),
    ]
