# Generated by Django 3.1.2 on 2020-10-08 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201008_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 13, 28, 28, 297484)),
        ),
    ]
