# Generated by Django 3.1.2 on 2020-10-08 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201008_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 14, 21, 17, 871524)),
        ),
    ]
