# Generated by Django 3.1.2 on 2020-10-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
