# Generated by Django 3.1.2 on 2020-10-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
